 #####################################################################
 # Example MPI C Makefile.
 #####################################################################
 
SRC = ecc
CC = g++-5.2.0

default:
	g++-5.2.0 ec.cpp ec_ops.cpp uberzahl.cpp -o ${SRC}
run:
	./${SRC}
clean:
	rm ${SRC}